#!/bin/bash
############################################################################## 
# IMPORTANT:  the next line determines how many nodes to run on 
#  nodes is number of nodes, ppn= processors (cores) per node
#PBS -l nodes=1:ppn=8
#PBS -l walltime=06:00:00
#PBS -V
#PBS -e error.log
#PBS -o output.log
# 
# Make sure that we are in the same subdirectory as where the qsub command 
# is issued. 
# 
cd $PBS_O_WORKDIR 
source $HOME/.bashrc
#
#  make a list of allocated nodes(cores)
#  Note that if multiple jobs run in same directory, use different names
#     for example, add on jobid nmber.
make clean
make 
mpirun -np 8 ./parties > log 
# 
#########################################
