void Conc_init_lock(Concentration *c, Cart3d_bag *data_bag, Debug_trace *dtrace);
void Conc_inititialize(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_sin(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_zero(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_RB(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_fullsin(Concentration *c, Cart3d_bag *data_bag);
void Conc_initialize_saltfinger ( Concentration **c, MAC_grid *grid, Parameters *params);
void Conc_init_xsin(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_cos(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_erf_x(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_erf_y(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_Ardekani(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_layer(int iconc, Concentration *c, Cart3d_bag *data_bag);
void Conc_init_unity(Concentration *c, Cart3d_bag *data_bag);
void Conc_init_intrusion_DD(int iconc, Concentration *c, Cart3d_bag *data_bag);
void Conc_init_intrusion_DD_partlock(int iconc, Concentration *c, Cart3d_bag *data_bag);
