#!bin/bash
## script to run validation cases 


################ the next lines are to be adapted for your enviroment
CODE='/home/thko6956/2017/PARTIES/Test-Particle/partest'  ## this is the code to be checked
INPUT_FILES='/home/thko6956/2017/PARTIES/Test-Particle/partest/input_files/validation'
VALI_DIR=$HOME/Validation${1}							## this is the path where the case are constructed in executed
echo $VALI_DIR
dojob='mpirun -np 4 ./parties >log'								## with this command the jobs are scheduled
#alias do_job='sbatch run_stampede2'

## put question that everything will be deleted in VALI_DIR

if [ ! -d "$VALI_DIR" ]
then
		mkdir ${VALI_DIR}
fi

################# Start with the cases

# settling in density gradient
if [ 1 = 0 ]
then
A=${INPUT_FILES}/ardekani_settling_v1_small
B=${VALI_DIR}/ardekani_settling_v1_small

	if [ -d "$B" ]; then
		rm -rf ${B}/*        #  $DIRECTORY exists.
	else
		mkdir ${B}
	fi

	rsync --exclude=*.h5 *.dat -rP ${CODE}/* ${B}/
	rsync -rP ${A}/parties.inp ${A}/p_mobile.inp  ${A}/p_fixed.inp 	${B}/
	rsync -rP ${A}/Boundary.h ${B}/src/Include/ 
	cd $B
	make clean
	make
	$dojob  

 
 fi
 
 
 
 
 
 
# heat transfer through channel
if [ 1 = 0 ]

then
A=${INPUT_FILES}/heat_channel_re05g01
B="${VALI_DIR}/heat_channel_re05g01"

	if [ -d "$B" ]; then
		rm -rf ${B}/*        #  $DIRECTORY exists.
	else
		mkdir ${B}
	fi

	rsync --exclude=*.h5 *.dat -rP ${CODE}/* ${B}/
	rsync -rP ${A}/parties.inp ${A}/p_mobile.inp  ${A}/p_fixed.inp 	${B}/
	rsync -rP ${A}/Boundary.h ${B}/src/Include/ 
	cd $B
	make clean
	make
	$dojob  
else

    command="heat_channel.m"
    echo ${command}
    cd ${INPUT_FILES}/matlab_analysis
    echo "source = ${VALI_DIR};" > tmp_script
    cat $command >> tmp_script
	cat tmp_script | matlab  -nodesktop -nodisplay -nosplash  
 fi
 
 
 # gravity current over bed
if [ 1 = 0 ] 
then
 
2+3 
 fi
 
 
 #mordant piton
 
if [ 1 = 0 ] 
then
 
 1+2
 fi
 
 
 #
 
 
 
 #gondret
 
if [ 1 = 0 ] 
then
 1+1
fi
 
 
 #
 
 
 
 
 
 
 